export const SPECIALIZATIONS = [
  'Allergist',
  'Anesthesiologist',
  'Audiologist',
  'Cardiologist',
  'Cardiothoracic Surgeon',
  'Chiropractor',
  'Dentist',
  'Dermatologist',
  'Endocrinologist',
  'ENT Specialist',
  'Family Medicine',
  'Gastroenterologist',
  'General Practitioner',
  'General Surgeon',
  'Geriatrician',
  'Gynecologist',
  'Hematologist',
  'Immunologist',
  'Infectious Disease Specialist',
  'Internal Medicine',
  'Neonatologist',
  'Nephrologist',
  'Neurologist',
  'Neurosurgeon',
  'Obstetrician',
  'Oncologist',
  'Ophthalmologist',
  'Optometrist',
  'Oral Surgeon',
  'Orthodontist',
  'Orthopedic Surgeon',
  'Otolaryngologist',
  'Pathologist',
  'Pediatrician',
  'Physiotherapist',
  'Plastic Surgeon',
  'Podiatrist',
  'Psychiatrist',
  'Psychologist',
  'Pulmonologist',
  'Radiologist',
  'Rheumatologist',
  'Sports Medicine Specialist',
  'Thoracic Surgeon',
  'Urologist',
  'Vascular Surgeon',
  'Veterinarian'
];
